config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  resources :books do
    resources :bookmarks, shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :bookmarks, dependent: :destroy

  validates :name, :author, presence: { message: '%{attribute} is mandatory' }
  validate :same_book_already_exist, on: :create

  # Return matched name or author based on (search) term
  def self.search(search_term)
    lowercase_term = search_term.downcase
    where('LOWER(name) LIKE ? OR LOWER(author) LIKE ?', "%#{lowercase_term}%", "%#{lowercase_term}%")
  end

  def same_book_already_exist
    matched_book = Book.where('LOWER(name) = LOWER(?) AND LOWER(author) = LOWER(?)', name, author)
    errors.add(:base, :same_book_exist, message: 'Book already exist') if matched_book.any?
  end

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :book

  validates :page_number, presence: { message: '%{attribute} is mandatory' }
  validates :page_number, numericality: { only_integer: true, message: 'Page number must be an integer'}
  validates :page_number, numericality: { greater_than: 0, message: 'Page number must be greater than %{value}'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  helper_method :book_id
  before_action :prepare_book, only: [:index, :new, :create]
  before_action :prepare_bookmark, only: [:show, :edit, :update, :destroy]

  def index
    @bookmarks = @book.bookmarks
    flash.now[:alert] = 'No bookmark found' if @bookmarks.empty?
  end

  def show
    @book = @bookmark.book
  end

  def new
    @bookmark = @book.bookmarks.build
  end

  def create
    # byebug
    @bookmark = @book.bookmarks.build(bookmark_params)
    if @bookmark.save
      flash[:notice] = 'Bookmark created successfully'
      redirect_to bookmark_path(@bookmark)
    else
      render :new
    end
  end

  def edit
    @book = @bookmark.book
  end

  def update
    if @bookmark.update(bookmark_params)
      flash[:notice] = 'Bookmark saved successfully'
      redirect_to bookmark_path(@bookmark)
    else
      render :edit
    end
  end

  def destroy
    @book = @bookmark.book
    @bookmark.destroy
    flash[:notice] = 'Bookmark deleted successfully'
    redirect_to book_bookmarks_path(@book)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:page_number, :description)
  end

  def prepare_book
    @book = Book.find(params[:book_id])
  end

  def prepare_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  helper_method :sort_column, :sort_direction, :search_params

  def index
    # byebug
    @books = if sort_column
               Book.search(search_params).order(sort_column + ' ' + sort_direction)
             elsif search_params
               Book.search(search_params).order(:name, :author)
             else
               Book.all.order(:name, :author)
             end
    flash[:alert] = 'Book not found'
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book added succesfully'
      # byebug
      redirect_to books_path
    else
      render :new
      # byebug
    end
  end

  def edit
    # byebug
    @book = Book.find(params[:id])
  end

  def update
    # byebug
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book updated succesfully'
      redirect_to books_path
    else
      # byebug
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'Book deleted succesfully'
    redirect_to books_path
  end

  private

  # Return book attributes in hash format
  def book_params
    params.require(:book).permit(:name, :author, :has_read)
  end

  # Return search term if exists, otherwise return nil
  def search_params
    params.dig(:search, :term)
  end

  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : nil
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : nil
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    icon_class = column == sort_column ? (sort_direction == 'asc' ? 'fa-caret-up' : 'fa-caret-down') : nil
    link_to sort: column, direction: direction, search: {term: search_params} do
      (title + ' ' + content_tag(:i, '', class: ['fa', icon_class], 'aria-hidden': 'true')).html_safe
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/edit(old).html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), book_bookmarks_path(@book) %>

    <h1 class='section-title text-center'>Edit Book</h1>

    <%= simple_form_for @bookmark, url: bookmark_path, method: :put do |f| %>
    <%= f.input :page_number, label: 'Page Number', placeholder: "E.g 38"%>
    <%= f.input :description, label: 'Description', placeholder: "Description" %>
    <%= f.button :submit, "Save" %>
    <% end %>

  </div>
</div>

app/views/bookmarks/edit.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), book_bookmarks_path(@book) %>

    <h1 class='section-title text-center'>Edit Book</h1>

    <%= simple_form_for @bookmark, url: bookmark_path, method: :put do |f| %>
    <%= f.input :page_number, label: 'Page Number', placeholder: "E.g 38"%>
    <%= f.input :description, label: 'Description', placeholder: "Description" %>
    <%= f.button :submit, "Save" %>
    <% end %>

  </div>
</div>

app/views/bookmarks/edit.html.slim
.container
  .jumbotron

    = link_to book_bookmarks_path(@book) do
      = image_tag 'icons/left_arrow', size: '25'

    h1.section-title.text-center Edit Book

    = simple_form_for @bookmark, url: bookmark_path, method: :put do |f|
      = f.input :page_number, label: 'Page Number', placeholder: "E.g 38"
      = f.input :description, label: 'Description', placeholder: "Description"
      = f.button :submit, "Save"

app/views/bookmarks/index.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), request.referer.present? ? request.referer : default_path %>

  </br>

  <div class='text-center'>
    <h1 class='section-title text-center'>My Bookmarks</h1>
    <p>Title: <%= @book.name %></p>
    <p>Author: <%= @book.author %></p>
  </div>

  <%= link_to image_tag('icons/new_book', size: '40'), new_book_bookmark_path(@book) %>

  <br />
  <p class='flash-notice text-center'><%= flash[:notice] %></p>
  <p class='flash-alert text-center'><%= flash[:alert] %></p>
  <br />

  <table class='table table-hover'>
    <thead>
      <tr>
        <th>#</th>
        <th>Page Number</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% count = 0 %>
      <% @bookmarks.each.with_index(1) do |bookmark, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= bookmark.page_number %></td>
        <td><%= bookmark.description %></td>
        <td><%= link_to image_tag('icons/show', size: '20'), bookmark_path(bookmark) %></td>
        <td><%= link_to image_tag('icons/edit', size: '20'), edit_bookmark_path(bookmark) %></td>
        <td><%= link_to image_tag('icons/delete', size: '20'), bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
</div>

app/views/bookmarks/new.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), book_bookmarks_path(@book) %>

    <h1 class='section-title text-center'>New Bookmark</h1>

    <ul class='help-block'>
      <% @bookmark.errors[:base].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>

    <%= simple_form_for @bookmark, url: book_bookmarks_path(@book), method: :post, html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :page_number, label: 'Page Number', placeholder: "E.g 38"%>
    <%= f.input :description, label: 'Description', placeholder: "Description" %>
    <%= f.button :submit, "Create" %>

    <% end %>

  </div>
</div>

app/views/bookmarks/show.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), book_bookmarks_path(@book) %>

    <p class='flash-notice text-center'><%= flash[:notice] %></p>

    <div class='text-center'>
      <h1 class='section-title'>Page Number: <%= @bookmark.page_number %></h1>
      <br />
      <p>Description: <%= @bookmark.description %></p>
      <p>Last updated: <%= @bookmark.updated_at %></p>
    </div>

  </div>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), books_path %>

    <h1 class='section-title text-center'>Edit Book</h1>

    <%= simple_form_for @book, url: book_path, method: :put do |f| %>
    <%= f.input :name, label: 'Name', placeholder: "Book's name", error: 'Name is mandatory' %>
    <%= f.input :author, label: 'Author', placeholder: "Author's name", error: 'Author is mandatory' %>
    <%= f.input :has_read, label: 'Read?' %>
    <%= f.button :submit, "Save" %>
    <% end %>

  </div>
</div>

app/views/books/index.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), root_path %>

  </br>

  <h1 class='section-title text-center'>My Reading List</h1>

  <br />

  <%= simple_form_for :search, url: books_path, method: :get do |f| %>
  <%= f.input :term, label: false, placeholder: "Search books or authors", input_html: {value: search_params} %>
  <%= f.button :submit, "Search", name: nil %>
  <%= link_to 'Full list', books_path %>
  <% end %>

  <br />
  <%= link_to image_tag('icons/new_book', size: '40'), new_book_path %>
  <p class='flash-notice text-center'><%= flash[:notice] %></p>
  <p class='flash-alert text-center'><%= flash[:alert] if @books.empty? %></p>
  <br />

  <table class='table table-hover'>
    <thead>
      <tr>
        <th>#</th>
        <th><%= sortable 'name' %></th>
        <th><%= sortable 'author' %></th>
        <th><%= sortable 'has_read', 'Read?' %></th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% count = 0 %>
      <% @books.each.with_index(1) do |book, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= image_tag('icons/checked', size: '20') if book.has_read %></td>
        <td><%= link_to image_tag('icons/show', size: '20'), book_path(book.id) %></td>
        <td><%= link_to image_tag('icons/edit', size: '20'), edit_book_path(book) %></td>
        <td><%= link_to image_tag('icons/bookmark', size: '20'), book_bookmarks_path(book) %></td>
        <td><%= link_to image_tag('icons/delete', size: '20'), book_path(book.id), method: :delete, data: { confirm: "Are you sure you want to delete #{book.name} by #{book.author}?" } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
</div>

app/views/books/new.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), books_path %>

    <h1 class='section-title text-center'>New Book</h1>

    <ul class='help-block'>
      <% @book.errors[:base].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>

    <%= simple_form_for @book, url: books_path, method: :post, html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :name, label: 'Name', placeholder: "Book's name"%>
    <%= f.input :author, label: 'Author', placeholder: "Author's name" %>
    <%= f.input :has_read, label: 'Read?' %>
    <%= f.button :submit, "Create" %>

    <% end %>

  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='jumbotron'>

    <%= link_to image_tag('icons/left_arrow', size: '25'), books_path %>

    <p class='flash-notice text-center'><%= flash[:notice] %></p>

    <div class='text-center'>
      <h1 class='section-title'><%= @book.name %></h1>
      <br />
      <p>Author: <%= @book.author %></p>
      <p><%= @book.has_read ? 'Already read' : 'Not yet read' %></p>
      <p>Last updated: <%= @book.updated_at %></p>
    </div>

    <br />

    <%= link_to 'View all bookmarks', book_bookmarks_path(@book) %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadingList</title>
    <%= csrf_meta_tags %>
    <script src="https://use.fontawesome.com/b5ea817148.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
    integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/color/jquery.color-2.1.2.js" integrity="sha256-1Cn7TdfHiMcEbTuku97ZRSGt2b3SvZftEIn68UMgHC8=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash|Delius+Unicase:700|Handlee" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<div class='quotes row justify-content-center'>
  <div class='col-10 col-md-6 text-center d-flex align-items-end justify-content-center'>
    <blockquote class="blockquote">
      <p class='mb-0'>You cannot open a book without learning something.</p>
      <footer class="blockquote-footer">Confucius</footer>
    </blockquote>
  </div>
  <div class='col-10 text-center d-flex align-items-center justify-content-center'>
    <%= link_to "My Reading List", books_path %>
  </div>
</div>